services:
  - type: web
    name: o2c-graph-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DB_PATH
        value: ../data/o2c.db
      - key: PYTHON_VERSION
        value: 3.11.0
